# Generated by Django 4.2.7 on 2023-12-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
        ('main', '0003_merge_20231214_1456'),
    ]

    operations = [
    ]
